language: c
sudo: required
dist: trusty
compiler:
- gcc
os:
- linux

branches:
  only:
  - master

before_script:
  - cd Programiraje2

script: ./run_all_test.sh

notifications:
  email:
    - rk7344@student.uni-lj.si

env:
  global:
  - LANG="en_US.UTF-8"