% Code generated by PREV compiler
SP	GREG	Stack_Segment
FP	GREG	#6100000000000000
	LOC	Data_Segment
DATA	GREG	@
_i	null,0
% Code Segment
	LOC	#500
Main	PUSHJ	$8,main
% STOPPING PROGRAM
	TRAP	0,Halt,0
% Code for function: _main
	%	 --- Prolog ---
main	SET	 $0,16
	%	 Storing FP 
	SUB	 $0,SP,$0
	STO	 FP,$0,0
	%	 STORING RA 
	GET	 $1,rJ
	STO	 $1,$0,8
	%	 Lowering FP 
	SET	 FP,SP
	%	 Lowering SP 
	SET	 $0,16
	SUB	 SP,SP,$0
	JMP	 L4
L4	SET	 $0,1
	SET	 $0,$0
	BZ	 $0,L3
L1	SET	 $0,1
	SET	 $0,$0
	SET	 $1, _i
	SET	 $1,$1
	STO	 $0,$1,0
	JMP	 L2
L3	SET	 $0,2
	SET	 $0,$0
	SET	 $1, _i
	SET	 $1,$1
	STO	 $0,$1,0
L2	SET	 $0,2
	SET	 $0,$0
	SET	 $1,3
	SET	 $1,$1
	DIV	 $0,$0,$1
	GET	 $0, $rR
	SET	 $0,$0
	JMP	 L5
	%	 --- Epilogue ---
L5	STO	 $0,FP,0  % Save return value 
	%	 Highering Stack pointer 
	SET	 SP,FP
	%	 Getting RA 
	SET	 $0,16
	SUB	 $0,SP,$0
	LDO	 $1,$0,8
	PUT	 rJ,$1
	%	 Getting old FP 
	LDO	 FP,$0,0
	POP	 8,0
