% Code generated by PREV compiler
SP	GREG	Stack_Segment
FP	GREG	#6100000000000000
	LOC	Data_Segment
DATA	GREG	@
_i	null,0
L0	"foo",0
% Code Segment
	LOC	#500
Main	PUSHJ	$8,main
% STOPPING PROGRAM
	TRAP	0,Halt,0
% Code for function: _p
	%	 --- Prolog ---
p	SET	 $0,24
	%	 Storing FP 
	SUB	 $0,SP,$0
	STO	 FP,$0,0
	%	 STORING RA 
	GET	 $1,rJ
	STO	 $1,$0,8
	%	 Lowering FP 
	SET	 FP,SP
	%	 Lowering SP 
	SET	 $0,40
	SUB	 SP,SP,$0
	JMP	 L3
L3	SET	 $0,0
	SET	 $0,0
	SET	 $0,$0
	SET	 $1, L0
	SET	 $1,$1
	STO	 $0,$254,0
	STO	 $1,$254,8
	PUSHJ	 $8,_printf
	LDO	 $0,$254,0
	JMP	 L4
	%	 --- Epilogue ---
L4	STO	 $0,FP,0  % Save return value 
	%	 Highering Stack pointer 
	SET	 SP,FP
	%	 Getting RA 
	SET	 $0,24
	SUB	 $0,SP,$0
	LDO	 $1,$0,8
	PUT	 rJ,$1
	%	 Getting old FP 
	LDO	 FP,$0,0
	POP	 8,0
